---
version: '3'

services:

  recipes:
    build:
      context: '.'
      args:
        app: 'recipes'
    environment:
      app: 'recipes'

  ingredients:
    build:
      context: '.'
      args:
        app: 'ingredients'
    environment:
      app: 'ingredients'

  menu:
    build:
      context: '.'
      args:
        app: 'menu'
    environment:
      app: 'menu'
    depends_on:
      - 'recipes'
      - 'ingredients'

  client:
    build:
      context: '.'
      args:
        app: 'client'
    environment:
      app: 'client'
    depends_on:
      - 'recipes'
      - 'ingredients'
      - 'menu'
    ports:
      - '80:8080'
