---
version: '3'

services:

  recipes:
    build:
      context: '.'
      dockerfile: 'Dockerfile-recipes'

  ingredients:
    build:
      context: '.'
      dockerfile: 'Dockerfile-ingredients'

  menu:
    build:
      context: '.'
      dockerfile: 'Dockerfile-menu'
    depends_on:
      - 'recipes'
      - 'ingredients'

  client:
    build:
      context: '.'
      dockerfile: 'Dockerfile-client'
    depends_on:
      - 'recipes'
      - 'ingredients'
      - 'menu'
    ports:
      - '80:8080'
