---
version: '3'

services:

  recipes:
    build:
      context: '.'
      dockerfile: 'Dockerfile-recipes'

  ingredients:
    build:
      context: '.'
      dockerfile: 'Dockerfile-ingredients'

  client:
    build:
      context: '.'
      dockerfile: 'Dockerfile-client'
    depends_on:
      - 'recipes'
      - 'ingredients'
    ports:
      - '80:8080'
