apiVersion: v1
kind: Service
metadata:
  name: ingredients
  labels:
    app: ingredients
    service: ingredients
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: ingredients
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingredients
  labels:
    app: ingredients
    version: v1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ingredients
    spec:
      containers:
      - image: localhost:5000/sandwiches-ingredients:v1
        name: ingredients
        resources: {}
        ports:
          - containerPort: 8080
      restartPolicy: Always
status: {}
