apiVersion: v1
kind: Service
metadata:
  name: menu
  labels:
    app: menu
    service: menu
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: menu
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: menu
  labels:
    app: menu
    version: v1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
      - image: localhost:5000/sandwiches-menu:v1
        name: menu
        resources: {}
        ports:
          - containerPort: 8080
      restartPolicy: Always
status: {}
